// Generated by CoffeeScript 2.4.1
(function() {
  "use strict";
  var fs, http;

  fs = require("fs");

  http = require("http");

  http.createServer(function(req, res) {
    switch (req.url) {
      case "/":
      case "/index":
      case "/index.html":
        res.writeHead(200, {
          "content-type": "text/html"
        });
        return fs.readFile("./dist/index.html", function(err, data) {
          return res.end(data);
        });
      case "/download":
        res.writeHead(200, {
          "Connection": "keep-alive",
          "content-type": "text/plain",
          "content-length": "5"
        });
        return [...Array(5)].reduce(function(promise, _, i) {
          return promise.then(function() {
            return new Promise(function(resolve) {
              return setTimeout(function() {
                res.write(String(i));
                return resolve();
              }, 3000);
            });
          });
        }, Promise.resolve()).then(function() {
          return res.end();
        });
    }
  }).listen(8080, function() {
    return console.log("Start http server 8080");
  });

}).call(this);
